name: Telegram Price Cron

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

# Memberikan izin akses tulis ke repositori agar git push berhasil
permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Telegram Update Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TARGET_CHAT_ID: ${{ secrets.TARGET_CHAT_ID }}
        run: python bot.py

      - name: Commit & Push Price History
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add last_prices.json
          git diff --staged --quiet || (git commit -m "Update last prices history [skip ci]" && git push)
